language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/bin/yes | pip uninstall numpy; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/science; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libopencv-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libboost-program-options-dev; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$OPENCV_VERSION" == "2" ]]; then brew install opencv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$OPENCV_VERSION" == "3" ]]; then brew install opencv3; fi

after_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$OPENCV_VERSION" == "3" ]]; then brew ln opencv3 --force; fi

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j4

matrix:
  include:
#    - os: linux
#      dist: trusty
#      compiler: g++
#      env: OPENCV_VERSION=2

#    - os: linux
#      dist: trusty
#      compiler: g++
#      env: OPENCV_VERSION=3
#     cache:
#        directories: $HOME/

#    - os: osx
#      compiler: clang++
#      env: OPENCV_VERSION=2

    - os: osx
      compiler: clang++
      env: OPENCV_VERSION=3
