language: cpp

matrix:
  include:
#    - os: linux
#      dist: trusty
#      compiler: g++
#      env: OPENCV_VERSION=2

    - os: linux
      dist: trusty
      compiler: g++
      env: OPENCV_VERSION=3
#      cache:
#        directories: $HOME/opencv-3.2.0

#    - os: osx
#      compiler: clang++
#      env: OPENCV_VERSION=2

#    - os: osx
#      compiler: clang++
#      env: OPENCV_VERSION=3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

  - if [[ "$TRAVIS_OS_NAME" ==   "osx" ]]; then /usr/bin/yes | pip uninstall numpy; fi
  - if [[ "$TRAVIS_OS_NAME" ==   "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" ==   "osx" ]]; then brew tap homebrew/science; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq libboost-program-options-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "2" ]]; then sudo apt-get install -qq libopencv-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "3" ]]; then sudo apt-get install -qq libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavresample-dev libavutil-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "3" ]]; then sudo apt-get install -qq libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libeigen3-dev; fi

  - if [[ "$TRAVIS_OS_NAME" ==   "osx" && "$OPENCV_VERSION" == "2" ]]; then brew install opencv; fi
  - if [[ "$TRAVIS_OS_NAME" ==   "osx" && "$OPENCV_VERSION" == "3" ]]; then brew install opencv3; fi
  - if [[ "$TRAVIS_OS_NAME" ==   "osx" && "$OPENCV_VERSION" == "3" ]]; then brew ln opencv3 --force; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "3" ]]; then WORKING_DIR="$(pwd)" && cd "$HOME"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "3" && ! -d "opencv-3.2.0" ]]; then INSTALL_OPENCV=1; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]]; then wget https://github.com/opencv/opencv/archive/3.2.0.tar.gz; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]]; then tar zxf 3.2.0.tar.gz; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]]; then cd opencv-3.2.0; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]]; then mkdir build; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]]; then cd build; fi
#  - if [[ "$INSTALL_OPENCV" == "1" ]];
    then
      wget https://github.com/opencv/opencv/archive/3.2.0.tar.gz;
      tar zxf 3.2.0.tar.gz;
      cd opencv-3.2.0;
      mkdir build;
      cd build;
      cmake -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=/usr/local
            -DWITH_OPENCL=OFF
            -DWITH_CUDA=OFF
            -DWITH_VTK=OFF
            -DWITH_MATLAB=OFF
            -DBUILD_opencv_java=OFF
            -DBUILD_opencv_python2=OFF
            -DBUILD_opencv_python3=OFF
            -DBUILD_TESTS=OFF
            -DBUILD_PERF_TESTS=OFF ..;
    fi
  - if [[ "$INSTALL_OPENCV" == "1" ]]; then make -j4; fi
  - if [[ "$INSTALL_OPENCV" == "1" ]]; then sudo make -j4 install; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$OPENCV_VERSION" == "3" ]]; then cd "$WORKING_DIR"; fi

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j4
